services:
  server:
    container_name: blipay-credit-server
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPEN_WEATHER_BASE_URL=http://api.openweathermap.org/data/2.5
      - OPEN_WEATHER_API_KEY=a1b2c3d4e5f6g7h8i9j0

  tests:
    container_name: blipay-credit-tests
    build: .
    command: hatch run test:test